services:
  aiostreams:
    image: ghcr.io/gabriel-prado/aiostreams:latest
    container_name: aiostreams
    restart: unless-stopped
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - ./data:/app/data
